name: Backend-Manual-Build-Push

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'

jobs:
  Backend-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate .env file from secrets
      run: |
        cat > backend/.env <<EOL
        BACKEND_PORT=${{ secrets.BACKEND_PORT }}
        SECRETKEY=${{ secrets.SECRETKEY }}
        TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}
        EMAIL_USER=${{ secrets.EMAIL_USER }}
        EMAIL_PASS=${{ secrets.EMAIL_PASS }}
        EOL

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image with build ID
      env:
        BUILD_ID: ${{ github.run_id }}
      run: |
        cd backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/real-estate-backend:${{ env.BUILD_ID }} .

    - name: Push Docker image to Docker Hub with build ID
      env:
        BUILD_ID: ${{ github.run_id }}
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/real-estate-backend:${{ env.BUILD_ID }}
