name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      build_id:
        description: 'Build number to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
        docker stop real-estate-backend || true
        docker rm real-estate-backend || true
        docker pull ${{ secrets.DOCKER_USERNAME }}/real-estate-backend:${{ github.event.inputs.build_id }}
        docker run -d --name real-estate-backend -p ${{ secrets.BACKEND_PORT }}:${{ secrets.BACKEND_PORT }} --network mern ${{ secrets.DOCKER_USERNAME }}/real-estate-backend:${{ github.event.inputs.build_id }}

