name: Backend-Manual-Deploy

on:
  workflow_dispatch:
    inputs:
      build_id:
        description: 'Build number to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        sudo usermod -aG docker ${{ secrets.VM_USER }}
        docker stop real-estate-frontend || true
        docker rm real-estate-frontend || true
        docker pull ${{ secrets.DOCKER_USERNAME }}/real-estate-frontend:${{ github.event.inputs.build_id }}
        docker run -d --name real-estate-backend -p 80:80 --network mern ${{ secrets.DOCKER_USERNAME }}/real-estate-frontend:${{ github.event.inputs.build_id }}
