name: Frontend-Manual-Build-Push

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'

jobs:
  frontend-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate .env file from secrets
      run: |
        cat > backend/.env <<EOL
        REACT_APP_BACKEND_PORT=${{ secrets.REACT_APP_BACKEND_PORT }}
        EOL

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image with build ID
      env:
        BUILD_ID: ${{ github.run_id }}
      run: |
        cd frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/real-estate-frontend:${{ env.BUILD_ID }} .

    - name: Push Docker image to Docker Hub with build ID
      env:
        BUILD_ID: ${{ github.run_id }}
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/real-estate-frontend:${{ env.BUILD_ID }}
